POST http://localhost:3000/player
Content-Type: application/json

{
  "section": "高校",
  "prefecture": "北海道",
  "name": "門別　啓人",
  "team": "東海大札幌",
  "position": "投手",
  "pitching_arm": "ほげ",
  "batting_arm": "左"
}